In [5]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']


def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]


list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [6]:
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True

In [7]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [s1+s2+n1+n2 for s1 in lowercase for s2 in lowercase for n1 in digits for n2 in digits]
answer[:3]

['aa00', 'aa01', 'aa02']

In [8]:
import numpy as np

In [10]:
test1 = np.random.randint(0, 10, (3,3))
test2 = test1 ** 2

In [11]:
for i, row in enumerate(test1):
    print('row', i, 'values', row)

row 0 values [9 9 8]
row 1 values [4 2 4]
row 2 values [6 9 7]


In [12]:
for i, j in zip(test1, test2):
    print(i, '+', j, '=', i+j)

[9 9 8] + [81 81 64] = [90 90 72]
[4 2 4] + [16  4 16] = [20  6 20]
[6 9 7] + [36 81 49] = [42 90 56]


In [13]:
 type(lambda x: x+1)

function

In [14]:
test1 = np.arange(36).reshape((6,6))
test1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
test1.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [17]:
test1[2:4,2:4]

array([[14, 15],
       [20, 21]])